### ISSUE TITLE
App crash first open after install from Play Store

### ISSUE THREAD

**Issue by luisfuertes** [ppsreejith/react-native-apps-flyer#18]
Hi, when i install my app from playstore with`react-native-apps-flyer` implemented, app crash.

Logcat:
**E/AndroidRuntime(11075): java.lang.RuntimeException: Unable to instantiate receiver com.google.android.apps.analytics.AnalyticsReceiver: java.lang.ClassNotFoundException: Didn't find class "com.google.android.apps.analytics.AnalyticsReceiver" on path: DexPathList[[zip file "/data/app/com.myproject-1/base.apk"],nativeLibraryDirectories=[/data/app/com.myproject-1/lib/arm, /vendor/lib, /system/lib]]**

I think i need Google analytics.
For use your component i had to edit your `android/build.gradle` and change this:
```
    compile 'com.google.android.gms:play-services-ads:+'
    compile 'com.google.android.gms:play-services-identity:+'
```

And for fix this last error i try to add in `react-native-apps-flyer` build.gradle: 
`compile "com.google.android.gms:play-services-analytics:+"`

But it doesnt fix component. 

I also try to add `compile "com.google.android.gms:play-services-analytics:+"`to my app/build.gradle but cant compile:
``` 
Found com.google.android.gms:play-services-analytics:+, but version 9.0.0 is needed for the google-services plugin.
:app:processReleaseGoogleServices FAILED
```

And with `compile "com.google.android.gms:play-services-analytics:9.0.0"` or 9.2.0 (last): 
``` 
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzlt;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzlt;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)
```

How can i fix it? Thanks

Full logcat of crash error:
``` 
D/AndroidRuntime(11075): Shutting down VM
E/AndroidRuntime(11075): FATAL EXCEPTION: main
E/AndroidRuntime(11075): Process: com.myproject, PID: 11075
E/AndroidRuntime(11075): java.lang.RuntimeException: Unable to instantiate receiver com.google.android.apps.analytics.AnalyticsReceiver: java.lang.ClassNotFoundException: Didn't find class "com.google.android.apps.analytics.AnalyticsReceiver" on path: DexPathList[[zip file "/data/app/com.myproject-1/base.apk"],nativeLibraryDirectories=[/data/app/com.myproject-1/lib/arm, /vendor/lib, /system/lib]]
E/AndroidRuntime(11075):  at android.app.ActivityThread.handleReceiver(ActivityThread.java:2623)
E/AndroidRuntime(11075):  at android.app.ActivityThread.access$1800(ActivityThread.java:154)
E/AndroidRuntime(11075):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
E/AndroidRuntime(11075):  at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(11075):  at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(11075):  at android.app.ActivityThread.main(ActivityThread.java:5292)
E/AndroidRuntime(11075):  at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11075):  at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(11075):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(11075):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime(11075): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.apps.analytics.AnalyticsReceiver" on path: DexPathList[[zip file "/data/app/com.myproject-1/base.apk"],nativeLibraryDirectories=[/data/app/com.myproject-1/lib/arm, /vendor/lib, /system/lib]]
E/AndroidRuntime(11075):  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(11075):  at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime(11075):  at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime(11075):  at android.app.ActivityThread.handleReceiver(ActivityThread.java:2618)
E/AndroidRuntime(11075):  ... 9 more
E/AndroidRuntime(11075):  Suppressed: java.lang.ClassNotFoundException: com.google.android.apps.analytics.AnalyticsReceiver
E/AndroidRuntime(11075):    at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(11075):    at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime(11075):    at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime(11075):    at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime(11075):    ... 11 more
E/AndroidRuntime(11075):  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
W/ActivityManager( 1571):   Force finishing activity 1 com.myproject/.MainActivity
```

**Comment by luisfuertes** [comment]
@ppsreejith you will fix it?

**Comment by mcabs3** [comment]
@luisfuertes have you tried doing a clean of your android project?

That usually fixed my `Cause: com.android.dex.DexException: Multiple dex files` issues

**Comment by rashdan** [comment]
+1
